### ISSUE TITLE
Eighties light contrast

### ISSUE THREAD

**Issue by tueksta** [avasconcelos114/mattermost-themes#48]
The active sidebar text on the eighties light theme is White #ffffff and the background is a very bright pastel #f2f0ec - the text is unreadable in that state. I switched sidebarTextActiveColor to #313131 for contrast, you might want to adjust this one here as well.

**Comment by avasconcelos114** [comment]
That's a great piece of feedback! I'll go ahead and change the color to the one you suggested :)

**Comment by avasconcelos114** [comment]
Fixed in https://github.com/avasconcelos114/mattermost-themes/pull/49

Thank you for your input!
